export enum WorkflowStatus {
  DRAFT = "DRAFT",
  PUBLISHED = "PUBLISHED",
}

export enum TaskType {
  FILE_UPLOADER = "FILE_UPLOADER",
  COMBINE_DATAFRAME = "COMBINE_DATAFRAME",
  SELECT_COLUMNS = "SELECT_COLUMNS",
  CATEGORY_ENCODER = "CATEGORY_ENCODER",
  NUMERIC_SCALER = "NUMERIC_SCALER",

  TRAIN_TEST_SPLIT = "TRAIN_TEST_SPLIT",
  TRAINING = "TRAINING",
  TUNING = "TUNING",
  EVALUATION = "EVALUATION",
  EMAIL_NOTIFICATION = "EMAIL_NOTIFICATION",
}

export enum TaskParamType {
  STRING = "STRING",
  FLOAT_NUMBER = "FLOAT_NUMBER",
  INTEGER_NUMBER = "INTEGER_NUMBER",
  BOOLEAN = "BOOLEAN",

  FILE = "FILE",

  TRIGGER = "TRIGGER",
  DATAFRAME = "DATAFRAME",
  COLUMN_SELECTOR = "COLUMN_SELECTOR",
  TRAIN_DATAFRAME = "TRAIN_DATAFRAME",
  TEST_DATAFRAME = "TEST_DATAFRAME",
  MODEL = "MODEL",
  REPORT = "REPORT",
}